DROP TABLE IF EXISTS quiz;

CREATE TABLE quiz (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  category VARCHAR(30) NOT NULL,
  question TEXT NOT NULL,
  correct_answer VARCHAR(50) NOT NULL,
  answer1 VARCHAR(50) NOT NULL,
  answer2 VARCHAR(50) NOT NULL,
  answer3 VARCHAR(50) NOT NULL,
  answer4 VARCHAR(50) NOT NULL
);